package telemetry

import "time"

// NodeStatus represents the operational status of a telemetry node.
type NodeStatus string

const (
	StatusNominal  NodeStatus = "nominal"
	StatusWarning  NodeStatus = "warning"
	StatusCritical NodeStatus = "critical"
	StatusOffline  NodeStatus = "offline"
)

// DeviceTelemetry represents simulated telemetry data generated by an edge node.
type DeviceTelemetry struct {
	NodeID       string     `json:"nodeId"`
	NodeName     string     `json:"nodeName"`
	NodeType     string     `json:"nodeType"` // e.g. "drone", "edge-sensor", "server", "gateway"
	Status       NodeStatus `json:"status"`
	BatteryPct   float64    `json:"batteryPct"`   // 0.0 - 100.0%
	TemperatureC float64    `json:"temperatureC"` // Celsius
	CPULoadPct   float64    `json:"cpuLoadPct"`   // 0.0 - 100.0%
	MemoryMB     float64    `json:"memoryMB"`     // Megabytes
	LatencyMs    float64    `json:"latencyMs"`    // Milliseconds
	ThroughputKb float64    `json:"throughputKb"` // Kbps
	PacketsSent  uint64     `json:"packetsSent"`
	SeqNumber    uint64     `json:"seqNumber"`
	Timestamp    time.Time  `json:"timestamp"`
}

// AlertEvent represents an incident or anomaly reported in real time.
type AlertEvent struct {
	ID        string     `json:"id"`
	NodeID    string     `json:"nodeId"`
	Severity  NodeStatus `json:"severity"`
	Message   string     `json:"message"`
	Metric    string     `json:"metric"`
	Value     float64    `json:"value"`
	Threshold float64    `json:"threshold"`
	Timestamp time.Time  `json:"timestamp"`
}
